### ISSUE TITLE
MalformedXML

### ISSUE THREAD

**Issue by celiovasconcelos** [triloknagvenkar/upload-audio-stream-to-aws-s3#1]
Hi,

Thank you for your code.

I'm getting `MalformedXML: The XML you provided was not well-formed or did not validate against our published schema` in the 4th request.

![Captura de Tela 2020-02-01 às 18 19 13](https://user-images.githubusercontent.com/849402/73599184-7952e580-451f-11ea-9377-1a03a9c38c3e.png)

Can you help me?

**Comment by KeysonG** [comment]
Having the exact same problem here.

**Comment by KeysonG** [comment]
Add this to your CORS configuration in your S3 Console

`<ExposeHeader>ETag</ExposeHeader>`

**Comment by triloknagvenkar** [comment]
@celiovasconcelos Please try updating the CORS configuration of the bucket.

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <ExposeHeader>ETag</ExposeHeader>
    <ExposeHeader>x-amz-meta-custom-header</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

**Comment by srijanTrilok** [comment]
Hey @celiovasconcelos,
I believe the above issue got resolved. Closing this issue.

Thanks.
