### ISSUE TITLE
s3.uploadPart response is empty {}

### ISSUE THREAD

**Issue by vineetiotina** [triloknagvenkar/upload-audio-stream-to-aws-s3#3]
Hi,
Can I trying to integrate this code in my project and got empty 'data'. Can anyone help me to fix it?
self.s3.uploadPart(params, function (err, data) {
      if (err) {
        console.log(err, err.stack);
      } // an error occurred
      else {
        console.log("Continue Upload:", data);
        /*
                    Once the part of data is uploaded we get an Entity tag for the uploaded object(ETag).
                    which is used later when we complete our multipart upload.
                */
        self.etag.push(data.ETag);
        if (self.booleanStop == true) {
          self.completeMultiUpload();
        }
      }
    });

Thanks

**Comment by srijanTrilok** [comment]
Hey @vineetiotina ,
I might need to go through the code to debug the issue you are facing.
Can you push the code to Github repo and share across so that I can debug the same

**Comment by vineetiotina** [comment]
Hi @srijanTrilok 
Nothing to push on repo, I just clone the repo then added the required credentials in the "html" file and run the code.

Thanks

**Comment by srijanTrilok** [comment]
Hey @vineetiotina,

I just tested the script on my system once again and it worked absolutely fine. Please make sure you are updating the below-mentioned values in the html file.
```
<script>
    var wRegion = "us-east-1";
    var poolid = "us-east-1:XXXXXXXXX";
    var s3bucketName = "BUCKET_NAME";
    var audioPath = "/audio-files";
    AudioStream = new AudioStream(wRegion,poolid,s3bucketName+audioPath);
    AudioStream.audioStreamInitialize();
  
  </script>

```

**Comment by vineetiotina** [comment]
Hi @srijanTrilok 
I just tested again and still got empty response on "self.s3.uploadPart", And yes I updated first three variables
var wRegion = "us-east-1";
var poolid = "us-east-1:XXXXXXXXX";
var s3bucketName = "BUCKET_NAME";

Thanks

**Comment by vineetiotina** [comment]
Hi @srijanTrilok 
My mistake I was not added etag into the core-configuration of the bucket. Now I have added and it's start working fine for me.
